name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["9.2.1"]
        cabal: ["3.6"]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal install -O2 --installdir bin
      - run: tar -cf lb.tar -C bin .
      - uses: actions/upload-artifact@v4
        with:
          name: lb-${{ runner.os }}
          path: lb.tar
